device: cuda

model_path: "./checkpoints/2025-03-24T18.03.13/ckpt-1-41.66-0.0027-2025-03-24T19.03.37.pt"

files:
  input_paths:
    - "./datasets/Kodak24"
  
  output_root_path: "./resources/inference"

inference:
  bm3d_sigma: 0.141
