device: cuda

dncnn_path: './checkpoints_dncnn/2025-03-29T01.32.04/ckpt-60-32.56-0.000018-2025-03-29T09.24.26.pt'
gradnet_bm3d_path: "./checkpoints/"
gradnet_dncnn_path: "./checkpoints/2025-03-29T16.43.15/ckpt-71-36.61-0.0004-2025-03-29T23.09.53.pt"
gradnet_mixup_dncnn_path: "./checkpoints/2025-03-30T04.43.20/ckpt-67-36.64-0.0004-2025-03-30T18.27.26.pt"

files:
  input_paths:
    ./datasets/Kodak24:
      type: awgn
      sigma: 0.098
    
    ./datasets/SIDD:
     type: real
     ref_path: ref
     noisy_path: noisy
  
  output_root_path: "./resources/inference"
  crop:
    height: 256
    width: 256
